# Generated by Django 6.0.3 on 2026-03-23 15:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_execlude_include_style_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='tour')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=50, null=True)),
                ('max_altitude', models.CharField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100, null=True)),
                ('accomodation', models.CharField(blank=True, max_length=100, null=True)),
                ('food', models.CharField(blank=True, max_length=100, null=True)),
                ('transpotation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('group_size', models.CharField(blank=True, max_length=100, null=True)),
                ('regular_price', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('overview', django_ckeditor_5.fields.CKEditor5Field()),
                ('route_map', models.ImageField(blank=True, null=True, upload_to='tour/map')),
                ('promotional_video', models.URLField(blank=True, help_text='Enter YouTube video URL', null=True)),
                ('gear_check_list', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.destination')),
                ('excludes', models.ManyToManyField(blank=True, null=True, to='core.execlude')),
                ('includes', models.ManyToManyField(blank=True, null=True, to='core.include')),
                ('style', models.ManyToManyField(blank=True, null=True, to='core.style')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
