# Generated by Django 6.0.3 on 2026-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_departure_faq_gallery_itinerary_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('solo', 'Travelling Solo'), ('couple', 'Travelling Couple'), ('family', 'Family Travelling'), ('group', 'Group Travelling')], max_length=20)),
                ('number_of_people', models.PositiveIntegerField(blank=True, null=True)),
                ('date_type', models.CharField(choices=[('have-date', 'I have My Date'), ('approx-date', 'I have Approx. Date'), ('no-date', 'Still Planning')], max_length=20)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('trip_choice', models.CharField(choices=[('preferred', 'I have my preferred trip'), ('expert-help', 'Need Expert Help')], max_length=20)),
                ('trip_selected', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_member', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravellersChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ManyToManyField(to='core.tour')),
            ],
        ),
    ]
