# Generated by Django 6.0.3 on 2026-04-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customizetrip_travellerschoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='icon',
        ),
    ]
