# Generated by Django 6.0.3 on 2026-04-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_style_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='starting_date',
        ),
    ]
