# Generated by Django 6.0.3 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tour_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
