# Generated by Django 6.0.3 on 2026-04-10 10:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tour_departure_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hightlight',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
