# Generated by Django 6.0.3 on 2026-04-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tour_hightlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='promotional_video',
        ),
    ]
