# Generated by Django 6.0.3 on 2026-04-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_tour_promotional_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='gear_check_list',
        ),
    ]
