# Generated by Django 6.0.3 on 2026-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
