# Generated by Django 5.2.3 on 2025-08-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
