# Generated by Django 5.2.3 on 2025-08-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
