# Generated by Django 6.0.2 on 2026-03-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
