# Generated by Django 6.0.3 on 2026-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytour',
            name='image',
            field=models.ImageField(upload_to='daytour'),
        ),
    ]
